// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppConfig {
    /**
     * Creates a new AppConfig instance.
     * @param {Partial<AppConfig>} [$$source = {}] - The source object to create the AppConfig.
     */
    constructor($$source = {}) {
        if (!("widgets" in $$source)) {
            /**
             * @member
             * @type {WidgetConfig[]}
             */
            this["widgets"] = [];
        }
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppConfig}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("widgets" in $$parsedSource) {
            $$parsedSource["widgets"] = $$createField0_0($$parsedSource["widgets"]);
        }
        return new AppConfig(/** @type {Partial<AppConfig>} */($$parsedSource));
    }
}

export class ModuleData {
    /**
     * Creates a new ModuleData instance.
     * @param {Partial<ModuleData>} [$$source = {}] - The source object to create the ModuleData.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {any}
             */
            this["value"] = null;
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModuleData instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModuleData}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ModuleData(/** @type {Partial<ModuleData>} */($$parsedSource));
    }
}

export class WidgetConfig {
    /**
     * Creates a new WidgetConfig instance.
     * @param {Partial<WidgetConfig>} [$$source = {}] - The source object to create the WidgetConfig.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["props"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WidgetConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WidgetConfig}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("props" in $$parsedSource) {
            $$parsedSource["props"] = $$createField2_0($$parsedSource["props"]);
        }
        return new WidgetConfig(/** @type {Partial<WidgetConfig>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = WidgetConfig.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
