// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppConfig {
    /**
     * Creates a new AppConfig instance.
     * @param {Partial<AppConfig>} [$$source = {}] - The source object to create the AppConfig.
     */
    constructor($$source = {}) {
        if (!("widgets" in $$source)) {
            /**
             * @member
             * @type {WidgetConfig[]}
             */
            this["widgets"] = [];
        }
        if (!("theme" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["theme"] = "";
        }
        if (!("minimalMode" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["minimalMode"] = false;
        }
        if (!("gridColumns" in $$source)) {
            /**
             * grid columns, default 2
             * @member
             * @type {number}
             */
            this["gridColumns"] = 0;
        }
        if (!("opacity" in $$source)) {
            /**
             * 0.1~1.0, default 0.72
             * @member
             * @type {number}
             */
            this["opacity"] = 0;
        }
        if (!("windowMode" in $$source)) {
            /**
             * "normal"|"locked"
             * @member
             * @type {string}
             */
            this["windowMode"] = "";
        }
        if (!("debugConsole" in $$source)) {
            /**
             * show debug console
             * @member
             * @type {boolean}
             */
            this["debugConsole"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppConfig}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("widgets" in $$parsedSource) {
            $$parsedSource["widgets"] = $$createField0_0($$parsedSource["widgets"]);
        }
        return new AppConfig(/** @type {Partial<AppConfig>} */($$parsedSource));
    }
}

export class WidgetConfig {
    /**
     * Creates a new WidgetConfig instance.
     * @param {Partial<WidgetConfig>} [$$source = {}] - The source object to create the WidgetConfig.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("enabled" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["props"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {WidgetLayout | null | undefined}
             */
            this["layout"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WidgetConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WidgetConfig}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType2;
        const $$createField3_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("props" in $$parsedSource) {
            $$parsedSource["props"] = $$createField2_0($$parsedSource["props"]);
        }
        if ("layout" in $$parsedSource) {
            $$parsedSource["layout"] = $$createField3_0($$parsedSource["layout"]);
        }
        return new WidgetConfig(/** @type {Partial<WidgetConfig>} */($$parsedSource));
    }
}

export class WidgetLayout {
    /**
     * Creates a new WidgetLayout instance.
     * @param {Partial<WidgetLayout>} [$$source = {}] - The source object to create the WidgetLayout.
     */
    constructor($$source = {}) {
        if (!("x" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["x"] = 0;
        }
        if (!("y" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["y"] = 0;
        }
        if (!("w" in $$source)) {
            /**
             * grid units width
             * @member
             * @type {number}
             */
            this["w"] = 0;
        }
        if (!("h" in $$source)) {
            /**
             * grid units height
             * @member
             * @type {number}
             */
            this["h"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new WidgetLayout instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {WidgetLayout}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new WidgetLayout(/** @type {Partial<WidgetLayout>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = WidgetConfig.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
const $$createType3 = WidgetLayout.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
