// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * ComponentType 定義所有支援的組件類型
 * @readonly
 * @enum {string}
 */
export const ComponentType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    TypeGauge: "gauge",
    TypeBarList: "bar-list",
    TypeKeyValue: "key-value",
    TypeGroup: "group",
    TypeSpark: "sparkline",
};

/**
 * ConfigSchema 定義單個設定欄位
 */
export class ConfigSchema {
    /**
     * Creates a new ConfigSchema instance.
     * @param {Partial<ConfigSchema>} [$$source = {}] - The source object to create the ConfigSchema.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * Action 按鈕可能不需要 name
             * @member
             * @type {string | undefined}
             */
            this["name"] = undefined;
        }
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {ConfigType}
             */
            this["type"] = ConfigType.$zero;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {any | undefined}
             */
            this["default"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 僅用於 select
             * @member
             * @type {SelectOption[] | undefined}
             */
            this["options"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 僅用於 button
             * @member
             * @type {string | undefined}
             */
            this["action"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConfigSchema instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConfigSchema}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("options" in $$parsedSource) {
            $$parsedSource["options"] = $$createField4_0($$parsedSource["options"]);
        }
        return new ConfigSchema(/** @type {Partial<ConfigSchema>} */($$parsedSource));
    }
}

/**
 * @readonly
 * @enum {string}
 */
export const ConfigType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    ConfigText: "text",
    ConfigNumber: "number",
    ConfigBool: "bool",
    ConfigSelect: "select",
    ConfigButton: "button",
};

/**
 * DataPayload 對應 WebSocket 推送或 HTTP Response
 */
export class DataPayload {
    /**
     * Creates a new DataPayload instance.
     * @param {Partial<DataPayload>} [$$source = {}] - The source object to create the DataPayload.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * 通用數值
             * 支援 number 或 string
             * @member
             * @type {any | undefined}
             */
            this["value"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Gauge 中心文字
             * @member
             * @type {string | undefined}
             */
            this["label"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * Sparkline 旁顯示文字
             * @member
             * @type {string | undefined}
             */
            this["displayValue"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 列表類數據 (BarList, KeyValue)
             * []BarItem 或 []KeyValueItem
             * @member
             * @type {any | undefined}
             */
            this["items"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 動態屬性覆蓋 (重點功能)
             * @member
             * @type {{ [_ in string]?: any } | undefined}
             */
            this["props"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DataPayload instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DataPayload}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("props" in $$parsedSource) {
            $$parsedSource["props"] = $$createField4_0($$parsedSource["props"]);
        }
        return new DataPayload(/** @type {Partial<DataPayload>} */($$parsedSource));
    }
}

/**
 * RenderConfig 對應 GetRenderConfig() 的回傳結構
 */
export class RenderConfig {
    /**
     * Creates a new RenderConfig instance.
     * @param {Partial<RenderConfig>} [$$source = {}] - The source object to create the RenderConfig.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * e.g., "glancehud.core.cpu"
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * e.g., "gauge"
             * @member
             * @type {ComponentType}
             */
            this["type"] = ComponentType.$zero;
        }
        if (!("title" in $$source)) {
            /**
             * e.g., "CPU Use"
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("props" in $$source)) {
            /**
             * 靜態設定 (min, max, unit...)
             * @member
             * @type {{ [_ in string]?: any }}
             */
            this["props"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RenderConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RenderConfig}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("props" in $$parsedSource) {
            $$parsedSource["props"] = $$createField3_0($$parsedSource["props"]);
        }
        return new RenderConfig(/** @type {Partial<RenderConfig>} */($$parsedSource));
    }
}

export class SelectOption {
    /**
     * Creates a new SelectOption instance.
     * @param {Partial<SelectOption>} [$$source = {}] - The source object to create the SelectOption.
     */
    constructor($$source = {}) {
        if (!("label" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["label"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SelectOption instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SelectOption}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SelectOption(/** @type {Partial<SelectOption>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = SelectOption.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = $Create.Map($Create.Any, $Create.Any);
