run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - ineffassign
    - unused

linters-settings:
  errcheck:
    check-type-assertions: true

issues:
  exclude-rules:
    # Allow unhandled errors in main/init patterns
    - linters: [errcheck]
      text: "Error return value of .*(Close|Flush|Write).*is not checked"
