// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * SystemStats holds the system performance metrics.
 */
export class SystemStats {
    /**
     * Creates a new SystemStats instance.
     * @param {Partial<SystemStats>} [$$source = {}] - The source object to create the SystemStats.
     */
    constructor($$source = {}) {
        if (!("cpuUsage" in $$source)) {
            /**
             * CPU usage percentage (0-100)
             * @member
             * @type {number}
             */
            this["cpuUsage"] = 0;
        }
        if (!("ramUsage" in $$source)) {
            /**
             * RAM usage percentage (0-100)
             * @member
             * @type {number}
             */
            this["ramUsage"] = 0;
        }
        if (!("ramTotal" in $$source)) {
            /**
             * Total RAM in GB
             * @member
             * @type {number}
             */
            this["ramTotal"] = 0;
        }
        if (!("ramUsed" in $$source)) {
            /**
             * Used RAM in GB
             * @member
             * @type {number}
             */
            this["ramUsed"] = 0;
        }
        if (!("diskUsage" in $$source)) {
            /**
             * Disk usage percentage (0-100)
             * @member
             * @type {number}
             */
            this["diskUsage"] = 0;
        }
        if (!("diskTotal" in $$source)) {
            /**
             * Total disk in GB
             * @member
             * @type {number}
             */
            this["diskTotal"] = 0;
        }
        if (!("diskUsed" in $$source)) {
            /**
             * Used disk in GB
             * @member
             * @type {number}
             */
            this["diskUsed"] = 0;
        }
        if (!("netUp" in $$source)) {
            /**
             * Upload speed KB/s
             * @member
             * @type {number}
             */
            this["netUp"] = 0;
        }
        if (!("netDown" in $$source)) {
            /**
             * Download speed KB/s
             * @member
             * @type {number}
             */
            this["netDown"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SystemStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SystemStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SystemStats(/** @type {Partial<SystemStats>} */($$parsedSource));
    }
}
