// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * SystemService now acts as the orchestrator
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as modules$0 from "./internal/modules/models.js";

/**
 * GetConfig returns the current app configuration.
 * @returns {$CancellablePromise<modules$0.AppConfig>}
 */
export function GetConfig() {
    return $Call.ByID(3513012090).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetSystemStats iterates over enabled modules and returns their data.
 * @returns {$CancellablePromise<modules$0.ModuleData[]>}
 */
export function GetSystemStats() {
    return $Call.ByID(847498860).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * SaveConfig updates and saves the configuration.
 * @param {modules$0.AppConfig} config
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(config) {
    return $Call.ByID(2652722943, config);
}

// Private type creation functions
const $$createType0 = modules$0.AppConfig.createFrom;
const $$createType1 = modules$0.ModuleData.createFrom;
const $$createType2 = $Create.Array($$createType1);
