// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as modules$0 from "./internal/modules/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as protocol$0 from "./internal/protocol/models.js";

/**
 * @returns {$CancellablePromise<modules$0.AppConfig>}
 */
export function GetConfig() {
    return $Call.ByID(3513012090).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetCurrentData returns the last cached data for all active modules
 * @returns {$CancellablePromise<{ [_ in string]?: protocol$0.DataPayload }>}
 */
export function GetCurrentData() {
    return $Call.ByID(2420040889).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetModuleConfigSchema returns the config schema for a specific module
 * @param {string} moduleID
 * @returns {$CancellablePromise<protocol$0.ConfigSchema[]>}
 */
export function GetModuleConfigSchema(moduleID) {
    return $Call.ByID(2223895245, moduleID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetModules returns the list of available modules and their render configs
 * @returns {$CancellablePromise<protocol$0.RenderConfig[]>}
 */
export function GetModules() {
    return $Call.ByID(3895809045).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * Keep GetSystemStats for backward compatibility or immediate fetch if needed
 * @returns {$CancellablePromise<any>}
 */
export function GetSystemStats() {
    return $Call.ByID(847498860);
}

/**
 * @param {modules$0.AppConfig} config
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(config) {
    return $Call.ByID(2652722943, config);
}

/**
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function Start(app) {
    return $Call.ByID(1339301388, app);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StartMonitoring() {
    return $Call.ByID(2618619198);
}

// Private type creation functions
const $$createType0 = modules$0.AppConfig.createFrom;
const $$createType1 = protocol$0.DataPayload.createFrom;
const $$createType2 = $Create.Map($Create.Any, $$createType1);
const $$createType3 = protocol$0.ConfigSchema.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = protocol$0.RenderConfig.createFrom;
const $$createType6 = $Create.Array($$createType5);
