// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as protocol$0 from "../protocol/models.js";

/**
 * ModuleInfo pairs the short config ID with the display RenderConfig.
 */
export class ModuleInfo {
    /**
     * Creates a new ModuleInfo instance.
     * @param {Partial<ModuleInfo>} [$$source = {}] - The source object to create the ModuleInfo.
     */
    constructor($$source = {}) {
        if (!("moduleId" in $$source)) {
            /**
             * short ID for config ("cpu","disk",...)
             * @member
             * @type {string}
             */
            this["moduleId"] = "";
        }
        if (!("config" in $$source)) {
            /**
             * display template
             * @member
             * @type {protocol$0.RenderConfig}
             */
            this["config"] = (new protocol$0.RenderConfig());
        }
        if (!("enabled" in $$source)) {
            /**
             * whether the module is active
             * @member
             * @type {boolean}
             */
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ModuleInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ModuleInfo}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField1_0($$parsedSource["config"]);
        }
        return new ModuleInfo(/** @type {Partial<ModuleInfo>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = protocol$0.RenderConfig.createFrom;
