// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../../../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as modules$0 from "../modules/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as protocol$0 from "../protocol/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * @returns {$CancellablePromise<modules$0.AppConfig>}
 */
export function GetConfig() {
    return $Call.ByID(1456817312).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * GetCurrentData returns the last cached data for all active modules
 * @returns {$CancellablePromise<{ [_ in string]?: protocol$0.DataPayload }>}
 */
export function GetCurrentData() {
    return $Call.ByID(760557991).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetModuleConfigSchema returns the config schema for a specific module.
 * Accepts either the short module ID ("disk") or the full render ID ("glancehud.core.disk").
 * @param {string} moduleID
 * @returns {$CancellablePromise<protocol$0.ConfigSchema[]>}
 */
export function GetModuleConfigSchema(moduleID) {
    return $Call.ByID(1777888183, moduleID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetModules returns the list of available modules with their short IDs, render configs, and enabled state.
 * @returns {$CancellablePromise<$models.ModuleInfo[]>}
 */
export function GetModules() {
    return $Call.ByID(837280723).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * Keep GetSystemStats for backward compatibility or immediate fetch if needed
 * @returns {$CancellablePromise<any>}
 */
export function GetSystemStats() {
    return $Call.ByID(3499803562);
}

/**
 * RegisterSidecar handles lazy registration.
 * If config is provided (template), it updates the sidecar definition.
 * If it's a new sidecar, it also adds it to the persistent config (enabled by default).
 * @param {string} id
 * @param {protocol$0.RenderConfig | null} config
 * @returns {$CancellablePromise<void>}
 */
export function RegisterSidecar(id, config) {
    return $Call.ByID(1279511238, id, config);
}

/**
 * @param {modules$0.AppConfig} config
 * @returns {$CancellablePromise<void>}
 */
export function SaveConfig(config) {
    return $Call.ByID(804382869, config);
}

/**
 * SetEditMode emits an edit mode toggle event to the frontend.
 * @param {boolean} enabled
 * @returns {$CancellablePromise<void>}
 */
export function SetEditMode(enabled) {
    return $Call.ByID(3057060141, enabled);
}

/**
 * SetWindowMode updates windowMode ("normal"|"locked") in config and emits mode:change event.
 * @param {string} mode
 * @returns {$CancellablePromise<void>}
 */
export function SetWindowMode(mode) {
    return $Call.ByID(154252141, mode);
}

/**
 * @param {application$0.App | null} app
 * @returns {$CancellablePromise<void>}
 */
export function Start(app) {
    return $Call.ByID(4086161138, app);
}

/**
 * @returns {$CancellablePromise<void>}
 */
export function StartMonitoring() {
    return $Call.ByID(3752777028);
}

/**
 * UpdateOpacity updates opacity in config and emits config:update event.
 * @param {number} opacity
 * @returns {$CancellablePromise<void>}
 */
export function UpdateOpacity(opacity) {
    return $Call.ByID(3549929656, opacity);
}

/**
 * UpdateSidecarData updates data for a sidecar module
 * @param {string} id
 * @param {protocol$0.DataPayload | null} data
 * @returns {$CancellablePromise<void>}
 */
export function UpdateSidecarData(id, data) {
    return $Call.ByID(1950429558, id, data);
}

// Private type creation functions
const $$createType0 = modules$0.AppConfig.createFrom;
const $$createType1 = protocol$0.DataPayload.createFrom;
const $$createType2 = $Create.Map($Create.Any, $$createType1);
const $$createType3 = protocol$0.ConfigSchema.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $models.ModuleInfo.createFrom;
const $$createType6 = $Create.Array($$createType5);
